restTemplate:
  ## HTTP超时时间
  conTimeout: 60
  readTimeout: 60
  ## 网关地址
  opbGatewayAddress: https://opbtest.bsngate.com:18602/api/2ad7f9e442e2401e8e885b30277724c3/rpc


contract:
  ## 查询交易回执前等待时间，单位为毫秒
  queryRecepitWaitTime: 200
  ## 查询交易回执重试次数
  queryRecepitRetryCount: 20